name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt
      - name: Run ShellCheck
        run: shellcheck update_crs_inplace.sh
      - name: Check shell formatting
        run: shfmt -d update_crs_inplace.sh
